CREATE DATABASE IF NOT EXISTS halisaha;
USE halisaha;

CREATE TABLE IF NOT EXISTS oyuncular (
  id INT AUTO_INCREMENT PRIMARY KEY,
  adSoyad VARCHAR(100) NOT NULL,
  pozisyon VARCHAR(50) NOT NULL,
  resim TEXT,
  yetenekler JSON,
  guc INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 
